/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1evpi3xznCu
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";

export function CreateInvoice() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-gray-900 text-white py-4 px-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <img
              alt="Company Logo"
              height={32}
              src="/placeholder.svg"
              style={{
                aspectRatio: "32/32",
                objectFit: "cover",
              }}
              width={32}
            />
            <span className="font-semibold text-lg">Acme Inc.</span>
          </div>
          <nav className="flex items-center gap-4">
            <Link className="hover:underline" href="#">
              Home
            </Link>
            <Link className="hover:underline" href="#">
              Invoices
            </Link>
            <Link className="hover:underline" href="#">
              Customers
            </Link>
          </nav>
        </div>
      </header>
      <main className="flex-1 py-8 px-6">
        <h1 className="text-2xl font-bold mb-6">Create Invoice</h1>
        <form className="bg-white shadow-md rounded-md p-6 space-y-6">
          <div className="grid grid-cols-2 gap-6">
            <div>
              <Label htmlFor="customer-name">Customer Name</Label>
              <Input id="customer-name" placeholder="John Doe" type="text" />
            </div>
            <div>
              <Label htmlFor="customer-email">Customer Email</Label>
              <Input
                id="customer-email"
                placeholder="john@example.com"
                type="email"
              />
            </div>
            <div>
              <Label htmlFor="customer-address">Customer Address</Label>
              <Textarea
                id="customer-address"
                placeholder="123 Main St, Anytown USA"
              />
            </div>
          </div>
          <div>
            <h2 className="text-lg font-semibold mb-4">Line Items</h2>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Description</TableHead>
                  <TableHead>Quantity</TableHead>
                  <TableHead>Price</TableHead>
                  <TableHead>Total</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>
                    <Input placeholder="Product or Service" type="text" />
                  </TableCell>
                  <TableCell>
                    <Input defaultValue="1" min="1" type="number" />
                  </TableCell>
                  <TableCell>
                    <Input
                      defaultValue="0.00"
                      min="0.00"
                      step="0.01"
                      type="number"
                    />
                  </TableCell>
                  <TableCell>$0.00</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>
                    <Input placeholder="Product or Service" type="text" />
                  </TableCell>
                  <TableCell>
                    <Input defaultValue="1" min="1" type="number" />
                  </TableCell>
                  <TableCell>
                    <Input
                      defaultValue="0.00"
                      min="0.00"
                      step="0.01"
                      type="number"
                    />
                  </TableCell>
                  <TableCell>$0.00</TableCell>
                </TableRow>
              </TableBody>
            </Table>
            <Button className="mt-4" size="sm" variant="outline">
              Add Line Item
            </Button>
          </div>
          <div className="grid grid-cols-2 gap-6">
            <div>
              <Label htmlFor="subtotal">Subtotal</Label>
              <Input
                defaultValue="0.00"
                disabled
                id="subtotal"
                min="0.00"
                step="0.01"
                type="number"
              />
            </div>
            <div>
              <Label htmlFor="tax">Tax</Label>
              <Input
                defaultValue="0.00"
                id="tax"
                min="0.00"
                step="0.01"
                type="number"
              />
            </div>
            <div>
              <Label htmlFor="total">Total</Label>
              <Input
                defaultValue="0.00"
                disabled
                id="total"
                min="0.00"
                step="0.01"
                type="number"
              />
            </div>
          </div>
          <div className="flex justify-end">
            <Button
              className="bg-gray-900 text-white hover:bg-gray-800"
              type="submit"
            >
              Save Invoice
            </Button>
          </div>
        </form>
      </main>
      <footer className="bg-gray-900 text-white py-4 px-6 mt-auto">
        <p className="text-sm">© 2024 Acme Inc. All rights reserved.</p>
      </footer>
    </div>
  );
}
